# Generated by Django 2.2.13 on 2020-08-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOutOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(verbose_name='Итого')),
                ('checkout_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_products', to='webapp.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='webapp.Product', verbose_name='Продукты'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40, verbose_name='Имя пользователя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер Телефона')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ManyToManyField(blank=True, related_name='orders', through='webapp.CheckOutOrder', to='webapp.Product', verbose_name='Продукт')),
            ],
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_orders', to='webapp.Order'),
        ),
    ]
