# Generated by Django 2.2.13 on 2020-08-31 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200831_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='total_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_amount', to='webapp.Cart'),
        ),
    ]
