# Generated by Django 2.2.13 on 2020-08-31 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200831_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='total_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_amount', to='webapp.Cart'),
        ),
    ]
